export const weather_dict = {
    "Sunny": "晴",
    "Clear": "晴",
    "Partly Cloudy": "多云",
    "Cloudy": "多云",
    "Overcast": "阴",
    "Mist": "雾霾",
    "Patchy rain nearby": "阵雨",
    "Patchy snow nearby": "阵雪",
    "Patchy sleet nearby": "雨夹雪",
    "Patchy freezing drizzle nearby": "冻雨",
    "Thundery outbreaks in nearby": "雷暴",
    "Blowing snow": "雪",
    "Blizzard": "暴雪",
    "Fog": "雾霾",
    "Freezing fog": "冻雾",
    "Patchy light drizzle": "小雨",
    "Light drizzle": "小雨",
    "Freezing drizzle": "冻雨",
    "Heavy freezing drizzle": "冻雨",
    "Patchy light rain": "阵雨",
    "Light rain": "小雨",
    "Moderate rain at times": "中雨",
    "Moderate rain": "中雨",
    "Heavy rain at times": "大雨",
    "Heavy rain": "大雨",
    "Light freezing rain": "冻雨",
    "Moderate or heavy freezing rain": "冻雨",
    "Light sleet": "雨夹雪",
    "Moderate or heavy sleet": "雨夹雪",
    "Patchy light snow": "阵雪",
    "Light snow": "小雪",
    "Patchy moderate snow": "阵雪",
    "Moderate snow": "中雪",
    "Patchy heavy snow": "阵雪",
    "Heavy snow": "大雪",
    "Ice pellets": "冰雹",
    "Light rain shower": "阵雨",
    "Moderate or heavy rain shower": "阵雨",
    "Torrential rain shower": "暴雨",
    "Light sleet showers": "雨夹雪",
    "Moderate or heavy sleet showers": "雨夹雪",
    "Light snow showers": "阵雪",
    "Moderate or heavy snow showers": "阵雪",
    "Light showers of ice pellets": "冰雹阵雨",
    "Moderate or heavy showers of ice pellets": "冰雹阵雨",
    "Patchy light rain in area with thunder": "雷暴",
    "Moderate or heavy rain in area with thunder": "雷暴",
    "Patchy light snow in area with thunder": "雷雪",
    "Moderate or heavy snow in area with thunder": "雷暴雪"
};

export const icon_dict = {
    "Sunny": "Sunny",
    "Clear": "ClearNight",
    "Partly cloudy": "Overcast",
    "Cloudy": "Overcast",
    "Overcast": "Overcast",
    "Mist": "Mist",
    "Patchy rain nearby": "ShowerRain2",
    "Patchy snow nearby": "SnowShower2",
    "Patchy sleet nearby": "Sleet2",
    "Patchy freezing drizzle nearby": "ShowerRain2",
    "Thundery outbreaks in nearby": "ThunderyRain",
    "Blowing snow": "LightSnow2",
    "Blizzard": "Blizzard2",
    "Fog": "Fog",
    "Freezing fog": "Fog",
    "Patchy light drizzle": "LightRain",
    "Light drizzle": "LightRain",
    "Freezing drizzle": "LightRain",
    "Heavy freezing drizzle": "HeavyRain",
    "Patchy light rain": "ShowerRain2",
    "Light rain": "LightRain",
    "Moderate rain at times": "ModerateRain",
    "Moderate rain": "ModerateRain",
    "Heavy rain at times": "HeavyRain",
    "Heavy rain": "HeavyRain",
    "Light freezing rain": "LightRain",
    "Moderate or heavy freezing rain": "ModerateRain",
    "Light sleet": "Sleet2",
    "Moderate or heavy sleet": "Sleet2",
    "Patchy light snow": "LightSnow",
    "Light snow": "LightSnow",
    "Patchy moderate snow": "ModerateSnow2",
    "Moderate snow": "ModerateSnow2",
    "Patchy heavy snow": "HeavySnow2",
    "Heavy snow": "HeavySnow2",
    "Ice pellets": "Sleet2",
    "Light rain shower": "ShowerRain2",
    "Moderate or heavy rain shower": "ShowerRain2",
    "Torrential rain shower": "TorrentialRain",
    "Light sleet showers": "Sleet2",
    "Moderate or heavy sleet showers": "Sleet2",
    "Light snow showers": "SnowShower2",
    "Moderate or heavy snow showers": "SnowShower2",
    "Light showers of ice pellets": "SnowShower2",
    "Moderate or heavy showers of ice pellets": "SnowShower2",
    "Patchy light rain with thunder": "ThunderyRain",
    "Moderate or heavy rain with thunder": "ThunderyRain",
    "Patchy light snow with thunder": "ThunderyRain",
    "Moderate or heavy snow with thunder": "ThunderyRain"
};