export const weather_dict = {
    "Sunny": "晴",
    "Clear": "晴",
    "Partly Cloudy": "多云",
    "Cloudy": "多云",
    "Overcast": "阴",
    "Mist": "雾霾",
    "Patchy rain nearby": "阵雨",
    "Patchy snow nearby": "阵雪",
    "Patchy sleet nearby": "雨夹雪",
    "Patchy freezing drizzle nearby": "冻雨",
    "Thundery outbreaks in nearby": "雷暴",
    "Blowing snow": "雪",
    "Blizzard": "暴雪",
    "Fog": "雾霾",
    "Freezing fog": "冻雾",
    "Patchy light drizzle": "小雨",
    "Light drizzle": "小雨",
    "Freezing drizzle": "冻雨",
    "Heavy freezing drizzle": "冻雨",
    "Patchy light rain": "阵雨",
    "Light rain": "小雨",
    "Moderate rain at times": "中雨",
    "Moderate rain": "中雨",
    "Heavy rain at times": "大雨",
    "Heavy rain": "大雨",
    "Light freezing rain": "冻雨",
    "Moderate or heavy freezing rain": "冻雨",
    "Light sleet": "雨夹雪",
    "Moderate or heavy sleet": "雨夹雪",
    "Patchy light snow": "阵雪",
    "Light snow": "小雪",
    "Patchy moderate snow": "阵雪",
    "Moderate snow": "中雪",
    "Patchy heavy snow": "阵雪",
    "Heavy snow": "大雪",
    "Ice pellets": "冰雹",
    "Light rain shower": "阵雨",
    "Moderate or heavy rain shower": "阵雨",
    "Torrential rain shower": "暴雨",
    "Light sleet showers": "雨夹雪",
    "Moderate or heavy sleet showers": "雨夹雪",
    "Light snow showers": "阵雪",
    "Moderate or heavy snow showers": "阵雪",
    "Light showers of ice pellets": "冰雹阵雨",
    "Moderate or heavy showers of ice pellets": "冰雹阵雨",
    "Patchy light rain in area with thunder": "雷暴",
    "Moderate or heavy rain in area with thunder": "雷暴",
    "Patchy light snow in area with thunder": "雷雪",
    "Moderate or heavy snow in area with thunder": "雷暴雪"
};

export const icon_dict = {
    "Sunny": "Sunny",
    "Clear": "ClearNight",
    "Partly Cloudy": "Overcast",
    "Cloudy": "Overcast",
    "Overcast": "Overcast",
    "Mist": "Mist",
    "Patchy Rain Nearby": "ShowerRain2",
    "Patchy Snow Nearby": "SnowShower2",
    "Patchy Sleet Nearby": "Sleet2",
    "Patchy Freezing Drizzle Nearby": "ShowerRain2",
    "Thundery Outbreaks In Nearby": "ThunderyRain",
    "Blowing Snow": "LightSnow2",
    "Blizzard": "Blizzard2",
    "Fog": "Fog",
    "Freezing Fog": "Fog",
    "Patchy Light Drizzle": "LightRain",
    "Light Drizzle": "LightRain",
    "Freezing Drizzle": "LightRain",
    "Heavy Freezing Drizzle": "HeavyRain",
    "Patchy Light Rain": "ShowerRain2",
    "Light Rain": "LightRain",
    "Moderate Rain At Times": "ModerateRain",
    "Moderate Rain": "ModerateRain",
    "Heavy Rain At Times": "HeavyRain",
    "Heavy Rain": "HeavyRain",
    "Light Freezing Rain": "LightRain",
    "Moderate Or Heavy Freezing Rain": "ModerateRain",
    "Light Sleet": "Sleet2",
    "Moderate Or Heavy Sleet": "Sleet2",
    "Patchy Light Snow": "LightSnow",
    "Light Snow": "LightSnow",
    "Patchy Moderate Snow": "ModerateSnow2",
    "Moderate Snow": "ModerateSnow2",
    "Patchy Heavy Snow": "HeavySnow2",
    "Heavy Snow": "HeavySnow2",
    "Ice Pellets": "Sleet2",
    "Light Rain Shower": "ShowerRain2",
    "Moderate Or Heavy Rain Shower": "ShowerRain2",
    "Torrential Rain Shower": "TorrentialRain",
    "Light Sleet Showers": "Sleet2",
    "Moderate Or Heavy Sleet Showers": "Sleet2",
    "Light Snow Showers": "SnowShower2",
    "Moderate Or Heavy Snow Showers": "SnowShower2",
    "Light Showers Of Ice Pellets": "SnowShower2",
    "Moderate Or Heavy Showers Of Ice Pellets": "SnowShower2",
    "Patchy Light Rain With Thunder": "ThunderyRain",
    "Moderate Or Heavy Rain With Thunder": "ThunderyRain",
    "Patchy Light Snow With Thunder": "ThunderyRain",
    "Moderate Or Heavy Snow With Thunder": "ThunderyRain"
};